### PR TITLE
Add CookieManager and cookie() functions and some optimize

### PR DESCRIPTION
**Pull request by huangzhhui**
1. Pull up `withContent()` and `withCookie()` methods from `Server Response` to `Base Response`

2. Add `RequestContext::get()` and `RequestContext::set()` alias methods for `RequestContext::getContextDataByKey()` and `RequestContext::setContextDataByKey()`

3. Add third argument `$rememberDefault` for `RequestContext::get()` method, it's a `BOOL` value, default value is `FALSE`, if this value is `TRUE`, then method will save `$default` by `$key` when default value been processed

4. Add `CookieManager` and `cookie()` functions for more easier to use Cookies in Controller

Usage:
1. Get the CookieManager of current request   
`\cookie()  `
> Note that the Container of CookieManager is bound with Request Context

2. Add Cookie to current Response   
`\cookie()->add($name, $value);   `
Other arguments are optional.

3. Remove a Cookie from container
`\cookie()->remove($name);`

4. Get all added Response Cookies
`\cookie()->all();   `
> Note that it's different with Request Cookies, here just the cookies that you added by CookieManager
> It is same way to get the Request Cookies, `$request->cookie()`
> Cause Request Cookies only provide Name and Value of Cookies, without other arguments, it is incomplete Cookie

### CODE REVIEW

**Comment by inhere** [comment]
我觉得 request() response() cookie() 这些该迁移到 http-server 里去

**Comment by huangzhhui** [comment]
cookie()我一开始是这样做了，但是后面发现这些是依赖RequestContext的，而RequestContext在framework项目，会变成http-server依赖framework项目，所以我就剥离了一下，让这些functions只是framework提供的一个便利

**Comment by inhere** [comment]
RequestContext 也该属于 httpServer 
不过现在就这样吧

**Comment by inhere** [comment]
太长？ `Swoft\Http\Server\RequestContext` 也不算长吧

**Comment by stelin** [comment]
这种快捷函数，还是放到对应的组件感觉好点。

**Comment by huangzhhui** [comment]
那就把RequestContext移到http server 去咯？

**Pull request merged**
